### ISSUE TITLE
wrong exit status

### ISSUE THREAD

**Issue by oliviertassinari** [nathanmarks/vrtest#1]
### Observation

https://github.com/callemall/material-ui/pull/6139 is introducing a regression
The visual regressions test outputs some error, still the exit status is fine 0.
>   Divider
    ✖  InsetDivider
    ✖  LightDivider
    ✖  SimpleDivider

### Expectation

The exit status should be 1 when the

**Comment by nathanmarks** [comment]
Hilarious.

**Comment by oliviertassinari** [comment]
I confirm the fix, awesome, thanks! https://github.com/callemall/material-ui/pull/6163
